/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author skyfindzz6
 */
public class NewJFrame extends javax.swing.JFrame {
    public double discount;
    public double rate;
    public final double hotelRoomRate = 1500;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMemberName = new javax.swing.JTextField();
        txtHotelRoomNo = new javax.swing.JTextField();
        txtNoDayStayed = new javax.swing.JTextField();
        txtAdditionalCharges = new javax.swing.JTextField();
        txtDiscountRate = new javax.swing.JTextField();
        txtDiscountAmount = new javax.swing.JTextField();
        txtHotelRoomCharge = new javax.swing.JTextField();
        txtTotalCharges = new javax.swing.JTextField();
        cbMemberType = new javax.swing.JComboBox<>();
        bntCompute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Member's Name");

        jLabel2.setText("Member Type");

        jLabel3.setText("Hotel Room No.");

        jLabel4.setText("No. of Days Stayed");

        jLabel5.setText("Additional Charges");

        jLabel6.setText("Discount Rate");

        jLabel7.setText("Discount Amount");

        jLabel8.setText("Hotel Room Charge");

        jLabel9.setText("Total Charges");

        txtDiscountAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountAmountActionPerformed(evt);
            }
        });

        cbMemberType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Gold", "Platinum" }));
        cbMemberType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemberTypeActionPerformed(evt);
            }
        });

        bntCompute.setText("COMPUTE");
        bntCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntComputeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMemberName)
                            .addComponent(txtHotelRoomNo)
                            .addComponent(txtNoDayStayed)
                            .addComponent(txtAdditionalCharges)
                            .addComponent(txtDiscountRate)
                            .addComponent(txtDiscountAmount)
                            .addComponent(txtHotelRoomCharge)
                            .addComponent(txtTotalCharges)
                            .addComponent(cbMemberType, 0, 127, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(bntCompute, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHotelRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoDayStayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAdditionalCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(bntCompute)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiscountRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHotelRoomCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiscountAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountAmountActionPerformed

    private void bntComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntComputeActionPerformed
        // TODO add your handling code here:
        /*
        
        txtMemberName;
        cbMemberType;
        txtHotelRoomNo;
        txtNoDayStayed;
        txtAdditionalCharges;
        
        txtDiscountRate;
        txtDiscountAmount;
        txtHotelRoomCharge;
        txtTotalCharges;
        
        */
        
        String NoDayStayed, AdditionalCharges, DiscountAmount, HotelRoomCharge, TotalCharges;
        double noDayStayed, additionalCharges, discountAmount, hotelRoomCharge, fhotelRoomCharge, totalCharges;
        
        
        //Text Conversions to double:
        noDayStayed = Double.parseDouble(txtNoDayStayed.getText());
        additionalCharges = Double.parseDouble(txtAdditionalCharges.getText());
        
        //Formula's:
        
        //Hotel Room Charge:
        hotelRoomCharge = noDayStayed * hotelRoomRate;
        
        //Discounted Amount: 
        discountAmount = hotelRoomRate * discount;
        
        //Final Hotel Room Charge after discount:
        fhotelRoomCharge = hotelRoomCharge - discountAmount;
        
        //Total Charges:
        totalCharges = fhotelRoomCharge + additionalCharges;
       
        
        //Conversion from double to String:
        DiscountAmount = String.format("%.2f", discountAmount);
        HotelRoomCharge = String.format("%.2f", fhotelRoomCharge);
        TotalCharges = String.format("%.2f", totalCharges);
        
        txtDiscountAmount.setText(DiscountAmount); 
        txtHotelRoomCharge.setText(HotelRoomCharge); 
        txtTotalCharges.setText(TotalCharges); 
        
        txtDiscountAmount.setEditable(false);
        txtHotelRoomCharge.setEditable(false);
        txtTotalCharges.setEditable(false);
            
    }//GEN-LAST:event_bntComputeActionPerformed

    private void cbMemberTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemberTypeActionPerformed
        // TODO add your handling code here:
        String selected;
        
        selected = (String) cbMemberType.getSelectedItem();
        
        if(selected == "Silver"){
            discount = 0.05;
            rate = hotelRoomRate * discount;
            System.out.println("Member Type: Silver");
            txtDiscountRate.setText("5%");
        }
        
        else if(selected == "Gold"){
            discount = 0.10;
            rate= hotelRoomRate * discount;
            System.out.println("Member Type: Gold");
            txtDiscountRate.setText("10%");
        }
        
        else{
            discount = 0.15;
            rate = hotelRoomRate * discount;
            System.out.println("Member Type: Platinum");
            txtDiscountRate.setText("15%");
        }
        
    }//GEN-LAST:event_cbMemberTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCompute;
    private javax.swing.JComboBox<String> cbMemberType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdditionalCharges;
    private javax.swing.JTextField txtDiscountAmount;
    private javax.swing.JTextField txtDiscountRate;
    private javax.swing.JTextField txtHotelRoomCharge;
    private javax.swing.JTextField txtHotelRoomNo;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtNoDayStayed;
    private javax.swing.JTextField txtTotalCharges;
    // End of variables declaration//GEN-END:variables
}
